name: Confluence Sync

on:
  workflow_dispatch:
  push:
    paths:
      - '**.md'
      - '!docs/docs-missing.md'
      - '!docs/other/click-icons.md'
      - '!docs/documentation.md'
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: kovetskiy/mark
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync to Confluence
        run: mark -k --drop-h1 -f '**.md' -b https://click-dealer.atlassian.net/wiki -u ${{ secrets.  }} -p ${{ secrets.MARK_PASSWORD }}
