name: Confluence Sync

on:
  workflow_dispatch:
  push:
    paths:
      - '**.md'
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: kovetskiy/mark
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync to Confluence
        run: for file in $(find -type f -name '*.md'); do
              echo "> Sync $file";
              { mark -k --drop-h1 -b https://click-dealer.atlassian.net/wiki -u ${{ secrets.MARK_USERNAME }} -p ${{ secrets.MARK_PASSWORD }} -f $file } || { echo "Missing headers..."; continue; };
              echo;
            done
